name: 'Create Release PR'

on:
  release:
    types: [published]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from release
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Released version: $VERSION"

      - name: Create pull request
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.extract_version.outputs.version }}';
            const tagName = `v${version}`;
            
            // Check if PR already exists
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:release`,
              base: 'main',
              state: 'open'
            });
            
            if (prs.length > 0) {
              console.log('Pull request already exists');
              return;
            }
            
            // Create PR
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Release ${tagName}`,
              head: 'release',
              base: 'main',
              body: `## Release ${tagName}

            This pull request contains the changes from the release branch for version ${version}.

            ### Changes
            - Version bump to ${version}
            - Built and released as ${tagName}

            ### Release Information
            - **Version**: ${version}
            - **Tag**: ${tagName}
            - **Release**: [${tagName}](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/tag/${tagName})

            This PR was automatically created after the successful release build.`
            });
            
            console.log(`Created pull request #${pr.number}: ${pr.html_url}`);
